/**
 * Created by pc on 2017/2/21.
 */
// 首页-轮播actions
export const FETCH_BANNER_HOME = 'FETCH_BANNER_HOME';
export const RECEIVE_BANNER_HOME = 'RECEIVE_BANNER_HOME'
export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const RECEIVE_PRODUCT_LIST = 'RECEIVE_PRODUCT_LIST'
export const FETCH_PRODUCT_DATA = 'FETCH_PRODUCT_DATA';
export const RECEIVE_PRODUCT_DATA = 'RECEIVE_PRODUCT_DATA';
export const FETCH_PRODUCT_ACCOUNT = 'FETCH_PRODUCT_ACCOUNT';
export const RECEIVE_PRODUCT_ACCOUNT = 'RECEIVE_PRODUCT_ACCOUNT';
export const FETCH_PRODUCT_AMOUNT = 'FETCH_PRODUCT_AMOUNT';
export const RECEIVE_PRODUCT_AMOUNT = 'RECEIVE_PRODUCT_AMOUNT'


